### ISSUE TITLE
Flashing Device fails using Mbed. 

### ISSUE THREAD

**Issue by RaysoftTechnologiesInc** [OpenNuvoton/NuMaker-Platform#3]
Hi, 
I recently purchased a Numaker-IoT-M487, How ever i am having issues flashing the board using Mbed Studio, I have made sure I set the VCOM and MSG switches as laid out in the documentation. I am not sure where I am going wrong here.

Please help...
![image](https://github.com/OpenNuvoton/NuMaker-Platform/assets/45296244/f1f11c4f-8250-4a28-bc6b-b9e8555cf927)

**Comment by cyliangtw** [comment]
About NuMaker-IoT-M487 & NuMaker-PFM-M487 board, the connector is Nu-Link and can't support pyOCD. So you can't flash or debug in Mbed Studio. Please manual drag & drop the bin file into NuMicro-MCU device.

If you need source level debug in Mbed Studio, please choose NuMaker-IoT-M467 or NuMkaer-M487KM board, the connector is Nu-Link2 and could support pyOCD.

**Comment by RaysoftTechnologiesInc** [comment]
Thank you for your response.

So I am trying to do source level debug, when I choose NuMaker-IoT-M467 I get this warning
![image](https://github.com/OpenNuvoton/NuMaker-Platform/assets/45296244/4ae2cb46-bd91-4877-9180-e521058c50a6)
because the board I have is a NuMaker-IoT-487. 

I also tried choosing the NuMaker-IoT-487, but it is still giving an error of flashing when I try to run the debugger.

**Comment by cyliangtw** [comment]
Yes, the system will detect the devic code and you should use the real NuMaker-IoT-M467 device.

On NuMaker-IoT-487 board, you can't burn/flash/debug the firmware(*.bin) by Mbed Studio.
You should copy the firmware(*.bin) into "NuMicro MCU" disk drive, such like the snapshot:
![image](https://github.com/OpenNuvoton/NuMaker-Platform/assets/14323432/79b72f0f-6c15-47d7-b968-b35692dc10b2)

**Comment by RaysoftTechnologiesInc** [comment]
So basically what you are saying is, If I am using the NuMaker-IoT-487 board, the only thing I can do is to drag the binary file to the NuMicro MCU disk drive, and I cannot run a debugger on this board? Am I correct?

**Comment by cyliangtw** [comment]
Yes, to drag & drop the bin file and you can't debug in Mbed Studio.

**Comment by RaysoftTechnologiesInc** [comment]
I also tried to run some example code I found on your website that was written using Keil IDE, however when I tried the example code I wasn't able to run it because the software pack does not include the M480 Devices, even though I installed them, How do I get past this?

I was trying to run the Intelligent Power Station example.

**Comment by CHHuang16** [comment]
[https://www.nuvoton.com/support/technical-support/faq/d97982a3-04f1-11ea-b113-05daf7eedf03/](https://www.nuvoton.com/support/technical-support/faq/d97982a3-04f1-11ea-b113-05daf7eedf03/)

Please try to follow the website description.
